applicationName: gdsc-collection-mirror
collectionName: {{ .Release.Name }}
nameSpace: gdsc-mirror
pullPolicy: IfNotPresent
storage:
  class: longhorn
  pvcs:
    data:
      name: data-store
      size: 3Gi
    postgis:
      name: postgis-data
      size: 3Gi
airflow:
  enabled: true
  redis:
    persistence:
      size: 1Gi # default 1Gi
  triggerer:
    persistence:
      size: 5Gi # default 100Gi
  workers:
    persistence:
      size: 5Gi # default 100Gi
  logs:
    persistence:
      size: 1Gi # default 100Gi

