applicationName: gdsc-collection-mirror
collectionName: {{ .Release.Name }}
ingress:
  enabled: true
  hostname: sub.domain.tld
  spec:
    ingressClassName: nginx
  tls: true
nameSpace: gdsc-mirror
pullPolicy: IfNotPresent
dataStore:
  persistence:
    storageClassName: "{{ .Release.Namespace }}-sc"
    size: 4Gi
postgis:
  persistence:
    storageClassName: "{{ .Release.Namespace }}-sc"
    size: 6Gi
airflow:
  enabled: true
  webserverSecretKeySecretName: dvmt-mirror-airflow-webserver-secret
  dags:
    gitSync:
      enabled: true
      repo: git@github.com:Geospatial-Digital-Special-Collections/airflow.git
      branch: main
      subPath: mirror
      sshKeySecret: ssh-git-secret
  config:
    webserver:
      base_url: https://.Values.ingress.hostname/.Release.Name/airflow
  redis:
    persistence:
      storageClassName: "{{ .Release.Namespace }}-sc"
      size: 1Gi # default 1Gi
  triggerer:
    persistence:
      storageClassName: "{{ .Release.Namespace }}-sc"
      size: 1Gi # default 100Gi
  workers:
    persistence:
      storageClassName: "{{ .Release.Namespace }}-sc"
      size: 1Gi # default 100Gi
  logs:
    persistence:
      storageClassName: "{{ .Release.Namespace }}-sc"
      size: 1Gi # default 100Gi
  # so airflow doesn't wait for database migration at start
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  # so airflow doesn't wait for database migration at start
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
  postgresql:
    primary:
      persistence:
        storageClassName: "{{ .Release.Namespace }}-sc"
        size: 1Gi # default 8Gi
    readReplicas:
      persistence:
        storageClassName: "{{ .Release.Namespace }}-sc"
        size: 1Gi # default 8Gi
    backup:
      persistence:
        storageClassName: "{{ .Release.Namespace }}-sc"
        size: 1Gi # default 8Gi
