applicationName: gdsc-collection-mirror
collectionName: "{{ .Release.Name }}"
ingressBase: https://r4-dev.idsc.miami.edu/
nameSpace: gdsc-mirror
pullPolicy: IfNotPresent
storage:
  class: longhorn
  pvcs:
    data:
      name: data-store
      size: 3Gi
    postgis:
      name: postgis-data
      size: 3Gi
airflow:
  enabled: true
  config:
    webserver:
      base_url: "https://r4-dev.idsc.miami.edu/{{ .Release.Name }}/airflow"
  redis:
    persistence:
      size: 1Gi # default 1Gi
  triggerer:
    persistence:
      size: 1Gi # default 100Gi
  workers:
    persistence:
      size: 1Gi # default 100Gi
  logs:
    persistence:
      size: 1Gi # default 100Gi
  # so airflow doesn't wait for database migration at start
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  # so airflow doesn't wait for database migration at start
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
  postgresql:
    primary:
      persistence:
        size: 1Gi # default 8Gi
    readReplicas:
      persistence:
        size: 1Gi # default 8Gi
    backup:
      persistence:
        size: 1Gi # default 8Gi
