nameSpace: gdsc-mirror
applicationName: gdsc-collection-mirror
collectionName: <name>
pullPolicy: IfNotPresent
storage: 
  class: "gdsc-mirror-sc"
  pvcs:
    data:
      name: data-store
      size: 20Gi
    postgis:
      name: postgis-data
      size: 10Gi
    airflow:
      name: airflow
      size: 20Mi
airflow:
  enabled: true
  workers:
    persistence:
      size: 5Gi # default 100Gi
  triggerer:
    persistence:
      size: 5Gi # default 100Gi
  redis:
    persistence:
      size: 1Gi # default 1Gi