applicationName: gdsc
ingress:
  enabled: true
  hostname: sub.domain.tld
  spec:
    ingressClassName: "nginx"
  tls: true
nameSpace: gdsc
pullPolicy: IfNotPresent
gdsc:
  storage: 
    provisioner: longhorn # can be one of [local-storage,rook-ceph,gdsc-sc,longhorn] default: longhorn
    cluster: true 
    data:
      persistence:
        size: 1Gi
    postgis:
      persistence:
        size: 1Gi
    collections:
      persistence:
        size: 10Mi
    solr:
      persistence:
        size: 100Mi
    tiles:
      persistence:
        size: 1Gi
    tileserv:
      persistence:
        size: 1Mi
    ohdsiVocabulary:
      persistence:
        size: 100Mi
airflow:
  enabled: true
  webserverSecretKeySecretName: gdsc-airflow-webserver-secret
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/Geospatial-Digital-Special-Collections/airflow.git
      branch: main
      rev: HEAD
      depth: 1
      subPath: gdsc
      knownHosts: |
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  config:
    webserver:
      base_url: https://.Values.ingress.hostname/.Release.Name/airflow
  redis:
    persistence:
      storageClassName: longhorn
      size: 1Gi # default 1Gi
  triggerer:
    persistence:
      storageClassName: longhorn
      size: 2Gi # default 100Gi
  workers:
    persistence:
      storageClassName: longhorn
      size: 2Gi # default 100Gi
  logs:
    persistence:
      storageClassName: longhorn
      size: 2Gi # default 100Gi
  postgresql:
    primary:
      persistence:
        storageClassName: longhorn
        size: 2Gi # default 8Gi
