apiVersion: v1
kind: Service
metadata:
  name: postgrest-{{ $.Values.collectionName }}
  labels: 
    app: postgrest-{{ $.Values.collectionName }}
spec:
  type: LoadBalancer
  selector:
    app: postgrest-{{ $.Values.collectionName }}
  ports:
   - port: 3000
     targetPort: 3000
     protocol: TCP