apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-collections
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/collections"