apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-airflow
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/airflow"