apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-tileserv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/tileserv"