apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-solr
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/solr"