apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-tiles
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/tiles"