apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/data"