apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nominatim-postgres
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 160Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/nominatim/postgres"