apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-postgis-geocode
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__path__/postgis_geocode"