apiVersion: v1
kind: Service
metadata:
  name: airflow-gdsc
  labels: 
    app: airflow-gdsc
spec:
  type: LoadBalancer
  selector:
    app: airflow-gdsc
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     protocol: TCP
