apiVersion: v1
kind: Service
metadata:
  name: flask-{{ .Release.Name }}
  labels: 
    app: flask-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: flask-{{ .Release.Name }}
  ports:
   - name: http-flask-{{ .Release.Name }}
     port: 5000
     targetPort: 5000
     protocol: TCP
