apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
  labels: 
    app: {{ .Release.Name }}-flask
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-flask
  ports:
   - name: http
     port: 5000
     targetPort: 5000
     protocol: TCP
