apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gdsc
  labels: 
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
   - name: http
     port: 5150
     targetPort: 80
     protocol: TCP