apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Release.Name }}
  labels: 
    app: nginx-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: nginx-{{ .Release.Name }}
  ports:
   - name: http-nginx-{{ .Release.Name }}
     port: 5150
     targetPort: 80
     protocol: TCP