apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels: 
    app: {{ .Release.Name }}-nginx
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
   - name: http
     port: 5150
     targetPort: 80
     protocol: TCP