apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgrest
  labels: 
    app: {{ .Release.Name }}-postgrest
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgrest
  ports:
   - name: http
     port: 3000
     targetPort: 3000
     protocol: TCP