apiVersion: v1
kind: Service
metadata:
  name: postgrest
  labels: 
    app: postgrest
spec:
  type: LoadBalancer
  selector:
    app: postgrest
  ports:
   - port: 3000
     targetPort: 3000
     protocol: TCP