apiVersion: v1
kind: Service
metadata:
  name: tileserv-{{ .Release.Name }}
  labels: 
    app: tileserv-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: tileserv-{{ .Release.Name }}
  ports:
   - name: http-tileserv-{{ .Release.Name }}
     port: 7800
     targetPort: 7800
     protocol: TCP
   - name: https-tileserv-{{ .Release.Name }}
     port: 7801
     targetPort: 7801
     protocol: TCP