apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tileserv
  labels: 
    app: {{ .Release.Name }}-tileserv
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-tileserv
  ports:
   - name: http
     port: 7800
     targetPort: 7800
     protocol: TCP
   - name: https
     port: 7801
     targetPort: 7801
     protocol: TCP