apiVersion: v1
kind: Service
metadata:
  name: postgis-proxy-{{ .Release.Name }}
  labels: 
    app: postgis-proxy-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: postgis-proxy-{{ .Release.Name }}
  ports:
   - name: http-postgis-proxy-{{ .Release.Name }}
     port: 5432
     targetPort: 5432
     protocol: TCP
  ##
   # NOTE: either port forward 
   # $ kubectl port-forward svc/postgis 5432:5432
   # $ psql -h localhost -p 5430 -U postgres
   # - or - 
   # get port from service
   # $ kubectl get svc postgis
   # $ psql -h localhost -p <port from output> -U postgres
   ##
