apiVersion: v1
kind: Service
metadata:
  name: solr-{{ .Release.Name }}
  labels: 
    app: solr-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: solr-{{ .Release.Name }}
  ports:
   - name: http-solr-{{ .Release.Name }}
     port: 8983
     targetPort: 8983
     protocol: TCP