apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solr
  labels: 
    app: {{ .Release.Name }}-solr
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-solr
  ports:
   - name: http
     port: 8983
     targetPort: 8983
     protocol: TCP