apiVersion: v1
kind: Service
metadata:
  name: solr
  labels: 
    app: solr
spec:
  type: LoadBalancer
  selector:
    app: solr
  ports:
   - name: http
     port: 8983
     targetPort: 8983
     protocol: TCP