apiVersion: v1
kind: Service
metadata:
  name: tileserver-gl-{{ .Release.Name }}
  labels: 
    app: tileserver-gl-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: tileserver-gl-{{ .Release.Name }}
  ports:
   - name: http-tileserver-gl-{{ .Release.Name }}
     port: 7810
     targetPort: 7810
     protocol: TCP