apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tileserver-gl
  labels: 
    app: {{ .Release.Name }}-tileserver-gl
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-tileserver-gl
  ports:
   - name: http
     port: 7810
     targetPort: 7810
     protocol: TCP