apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
  namespace: gdsc
  labels:
    app: {{ .Release.Name }}-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      imagePullSecrets:
        - name: docker-hub-cred 
      containers:
        - name: flask
          image: tibben/pg:repository
          imagePullPolicy: {{ $.Values.pullPolicy }}
          ports:
            - containerPort: 5000 
          command: ["/bin/sh"]
          args: ["-c","tail -F /dev/null"]
          #command: ["/bin/sh"]
          #args: ["-c", "cd /gdsc && uvicorn --port 5000 --reload gdsc:app"]
          volumeMounts:
            - name: data-pvc
              mountPath: /data
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
