apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      serviceAccountName: gdsc-controller
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: tiles-pvc
              mountPath: /usr/share/nginx/html/tiles
          ports:
          - containerPort: 80
      volumes:
        - name: tiles-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiles
