apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserv-{{ .Release.Name }}
  labels:
    app: tileserv-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tileserv-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: tileserv-{{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      containers:
        - name: tileserv-{{ .Release.Name }}
          image: pramsey/pg_tileserv:20240131
          ports:
            - containerPort: 7800
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: POSTGRES_DB
            - name: DB_AUTHENTICATOR_USER
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: DB_AUTHENTICATOR_USER
            - name: DB_AUTHENTICATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: DB_AUTHENTICATOR_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(DB_AUTHENTICATOR_USER):$(DB_AUTHENTICATOR_PASSWORD)@postgis-proxy/$(POSTGRES_DB)
          volumeMounts:
            - name: tileserv-assets
              mountPath: /app/assets
      volumes:
        - name: tileserv-assets
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tileserv
