apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgis-proxy
  labels:
    app: {{ .Release.Name }}-postgis-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgis-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgis-proxy
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      imagePullSecrets:
        - name: docker-hub-cred 
      containers:
        - name: {{ .Release.Name }}-postgis-proxy
          image: tibben/pg:proxy
          imagePullPolicy: {{ $.Values.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: LD_LIBRARY_PATH
              value: /usr/lib/postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: POSTGRES_PASSWORD
            - name: SDE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: SDE_PASSWORD
            - name: DB_AUTHENTICATOR_USER
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: DB_AUTHENTICATOR_USER
            - name: DB_AUTHENTICATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: DB_AUTHENTICATOR_PASSWORD
#          volumeMounts:
#            - name: postgis-proxy-pvc
#              mountPath: /var/lib/postgresql/data
#      volumes:
#        - name: postgis-proxy-pvc
#          persistentVolumeClaim:
#            claimName: {{ .Release.Name }}-postgis
