apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      serviceAccountName: gdsc-controller
      containers:
        - name: solr
          image: solr
          imagePullPolicy: IfNotPresent
          env:
            - name: SOLR_HEAP
              value: 1g
          ports:
            - containerPort: 8983 
          resources:
            requests:
              memory: 2Gi
          volumeMounts:
            - name: solr-ceph-pvc
              mountPath: /var/solr/data
            - name: data-ceph-pvc
              mountPath: /data
            - name: collections-ceph-pvc
              mountPath: /collections
      volumes:
        - name: solr-ceph-pvc
          persistentVolumeClaim:
            claimName: solr-ceph
        - name: data-ceph-pvc
          persistentVolumeClaim:
            claimName: data-ceph
        - name: collections-ceph-pvc
          persistentVolumeClaim:
            claimName: collections-ceph
