apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      containers:
        - name: solr
          image: solr
          imagePullPolicy: {{ $.Values.pullPolicy }}
          env:
            - name: SOLR_HEAP
              value: 1g
          ports:
            - containerPort: 8983 
          resources:
            requests:
              memory: 2Gi
          volumeMounts:
            - name: solr-pvc
              mountPath: /var/solr/data
            - name: data-pvc
              mountPath: /data
            - name: collections-pvc
              mountPath: /collections
      volumes:
        - name: solr-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-solr
        - name: data-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
        - name: collections-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-collections
