apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tileserver-gl
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tileserver-gl
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tileserver-gl
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      containers:
        - name: tileserver-gl
          image: maptiler/tileserver-gl
          command: ["/bin/sh"]
          args: ["-c","tail -F /dev/null"]
          volumeMounts:
            - name: tiles-pvc
              mountPath: /tiles
          ports:
            - containerPort: 7810
      volumes:
        - name: tiles-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiles
