apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver-gl-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: tileserver-gl-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: tileserver-gl-{{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-controller
      containers:
        - name: tileserver-gl-{{ .Release.Name }}
          image: maptiler/tileserver-gl
          command: ["/bin/sh"]
          args: ["-c","tail -F /dev/null"]
          volumeMounts:
            - name: tiles-pvc
              mountPath: /tiles
          ports:
            - containerPort: 7810
      volumes:
        - name: tiles-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiles
