apiVersion: v1
kind: Service
metadata:
  name: postgrest-{{ $.Values.collectionName }}
  labels: 
    app: postgrest-{{ $.Values.collectionName }}
spec:
  type: ClusterIP
  selector:
    app: postgrest-{{ $.Values.collectionName }}
  ports:
   - name: http-postgrest-{{ $.Values.collectionName }}
     port: 3000
     targetPort: 3000
     protocol: TCP