apiVersion: v1
kind: Service
metadata:
  name: postgrest-{{ .Release.Name }}
  labels: 
    app: postgrest-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: postgrest-{{ .Release.Name }}
  ports:
   - name: postgrest-{{ .Release.Name }}
     port: 3000
     targetPort: 3000
     protocol: TCP