apiVersion: v1
kind: Service
metadata:
  name: postgis-{{ $.Values.collectionName }}
  labels: 
    app: postgis-{{ $.Values.collectionName }}
spec:
  type: ClusterIP
  selector:
    app: postgis-{{ $.Values.collectionName }}
  ports:
   - name: http-postgis-{{ $.Values.collectionName }}
     port: 5432
     targetPort: 5432
     protocol: TCP
