apiVersion: v1
kind: Service
metadata:
  name: postgis-{{ $.Values.collectionName }}
  labels: 
    app: postgis-{{ $.Values.collectionName }}
spec:
  type: LoadBalancer
  selector:
    app: postgis-{{ $.Values.collectionName }}
  ports:
   - port: 5432
     targetPort: 5432
     protocol: TCP
