apiVersion: v1
kind: Service
metadata:
  name: postgis-{{ .Release.Name }}
  labels: 
    app: postgis-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: postgis-{{ .Release.Name }}
  ports:
   - name: postgis-{{ .Release.Name }}
     port: 5432
     targetPort: 5432
     protocol: TCP
