apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-flatnode
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: local-nominatim-flatnode