apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-geocode
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 100Gi
  volumeName: local-postgis-geocode