apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-ceph
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 20Mi
  volumeName: local-airflow