apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Release.Name }}-sc
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.gdsc.storage.data.persistence.size }}
