apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-postgis
spec:
  storageClassName: {{ .Release.Name }}-sc
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.gdsc.storage.postgis.persistence.size }}
