apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ $.Values.dataStore.persistence.name }}
spec:
  storageClassName: {{ $.Values.dataStore.persistence.storageClass }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.dataStore.persistence.size }}
