apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-{{ $.Values.storage.pvcs.data.name }}
spec:
  storageClassName: {{ $.Values.storage.class }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.storage.pvcs.data.size }}
