apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-postgis-data
spec:
  storageClassName: {{ $.Values.postgis.persistence.storageClassName }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.postgis.persistence.size }}
