apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-postgres
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 160Gi
  volumeName: local-nominatim-postgres