apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collections-ceph
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: local-collections