apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-ceph
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 100Mi
  volumeName: local-solr