apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-ohdsi-vocabulary
spec:
  storageClassName: {{ .Release.Name }}-sc
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests: 
      storage: {{ $.Values.gdsc.storage.ohdsiVocabulary.persistence.size }}
