apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgis
  name: collections-ceph
  namespace: gdsc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
