apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgis
  name: data-ceph
  namespace: gdsc
spec:
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
