apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgis
  name: postgis-ceph
  namespace: gdsc
spec:
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30720Mi
