apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgis-vocabulary
  name: postgis-vocabulary-ceph
  namespace: gdsc
spec:
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests: 100Mi
