apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: solr
  name: solr-ceph
  namespace: gdsc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
