apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgis-tileserv
  name: tileserv-ceph
  namespace: gdsc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
