apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ $.Values.applicationName }}
  name: {{ .Release.Name }}-collections
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Release.Namespace }}-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.gdsc.storage.collections.persistence.size }}
