apiVersion: v1
kind: Service
metadata:
  name: airflow-{{ .Release.Name }}
  labels: 
    app: airflow-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: airflow-{{ .Release.Name }}
  ports:
   - name: airflow-{{ .Release.Name }}
     port: 8080
     targetPort: 8080
     protocol: TCP
