apiVersion: v1
kind: Service
metadata:
  name: geoblacklight
  namespace: gdsc
  labels: 
    app: geoblacklight
spec:
  type: LoadBalancer
  selector:
    app: geoblacklight
  ports:
   - name: solr-http
     port: 8983
     targetPort: 8983
     protocol: TCP
   - name: geoblacklight-http
     port: 3000
     targetPort: 3000
     protocol: TCP