apiVersion: v1
kind: Service
metadata:
  name: postgis-vocab
  namespace: gdsc
  labels: 
    app: postgis-vocab
spec:
  type: LoadBalancer
  selector:
    app: postgis-vocab
  ports:
   - port: 5432
     targetPort: 5432
     protocol: TCP
  ##
   # NOTE: either port forward 
   # $ kubectl port-forward svc/postgis-vocab -n gdsc 5430:5432
   # $ psql -h localhost -p 5430 -U postgres
   # - or - 
   # get port from service
   # $ kubectl get svc postgis-vocab -n gdsc
   # $ psql -h localhost -p <port from output> -U postgres
   ##
